# Generated by Django 4.2.16 on 2026-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('args', models.JSONField(default=list)),
                ('kwargs', models.JSONField(default=dict)),
                ('exception_type', models.CharField(max_length=255)),
                ('exception_message', models.TextField()),
                ('traceback', models.TextField(blank=True, default='')),
                ('retries_attempted', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_name', '-created_at'], name='section2_qu_task_na_daad99_idx')],
            },
        ),
    ]
