[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts = -v --reuse-db
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    redis: marks tests that require a live Redis instance
